# Suppress maximize for all windows
windowrule = suppress_event maximize, match:class .*

# Tag all windows for default opacity
windowrule = tag +default-opacity, match:class .*

# Fix XWayland dragging
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Apply default opacity
windowrule = opacity 0.97 0.9, match:tag default-opacity

# Floating TUI windows
windowrule = float on,     match:class (FloatTerm)
windowrule = center on,    match:class (FloatTerm)
windowrule = size 800 600, match:class (FloatTerm)
