# Terminal
$terminal = uwsm app -- foot

# App launchers
bindd = SUPER, return, Terminal, exec, $terminal
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, omyfendory-launch-browser
bindd = SUPER SHIFT, B, Browser private, exec, omyfendory-launch-browser --private-window
bindd = SUPER, M, Music, exec, omyfendory-launch-or-focus spotify "uwsm app -- flatpak run com.spotify.Client"
bindd = SUPER, N, Editor, exec, uwsm app -- foot -e nvim
bindd = SUPER, T, Activity, exec, uwsm app -- foot --app-id=FloatTerm -e btop
bindd = SUPER SHIFT, D, Docker, exec, uwsm app -- foot --app-id=FloatTerm -e lazydocker
bindd = SUPER, O, Obsidian, exec, omyfendory-launch-or-focus obsidian "uwsm app -- flatpak run md.obsidian.Obsidian"
bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

# Webapps
bindd = SUPER, A, ChatGPT, exec, omyfendory-launch-webapp "https://chatgpt.com"
bindd = SUPER, Y, YouTube, exec, omyfendory-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER, W, WhatsApp, exec, omyfendory-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER ALT, G, Google Messages, exec, omyfendory-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER, D, PDF Viewer, exec, uwsm app -- zathura
bindd = SUPER, E, Edge, exec, uwsm app -- flatpak run com.microsoft.Edge
bindd = SUPER, C, CorreoUCR, exec, omyfendory-launch-webapp "https://correo.ucr.ac.cr"
bindd = SUPER SHIFT, C, GMail, exec, omyfendory-launch-webapp "https://gmail.com"
bindd = SUPER, G, MyGitea, exec, omyfendory-launch-webapp "https://gitea.luisumana.top"
bindd = SUPER SHIFT, G, Github, exec, omyfendory-launch-webapp "https://github.com"
bindd = SUPER, I, Inkscape, exec, uwsm app -- flatpak run org.inkscape.Inkscape
bindd = SUPER SHIFT, P, Python, exec, uwsm app -- foot --app-id=FloatTerm -e python3
bindd = SUPER, Z, Zotero, exec, uwsm app -- flatpak run org.zotero.Zotero

# Clipboard
bindd = SUPER CTRL, V, Clipboard history, exec, wl-paste -l | wofi --dmenu | wl-copy

# Copy / Paste universal
bindd = SUPER ALT, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER ALT, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER ALT, X, Universal cut, sendshortcut, CTRL, X,
